// Exposes a narrow, promise-based API to the renderer.
const { contextBridge, ipcRenderer, webUtils } = require('electron');

const invoke = (ch) => (...args) => ipcRenderer.invoke(ch, ...args);
const on = (ch) => (cb) => {
  const listener = (_e, payload) => cb(payload);
  ipcRenderer.on(ch, listener);
  return () => ipcRenderer.removeListener(ch, listener);
};

// ?mock=1 (dev only) leaves window.api to the renderer's demo backend.
if (!new URLSearchParams(location.search).has('mock')) contextBridge.exposeInMainWorld('api', {
  isElectron: true,
  platform: process.platform,
  pathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return null; } },

  app: {
    info: invoke('app:info'),
    resolveTools: invoke('app:resolveTools'),
    setTitleBar: invoke('app:setTitleBar'),
    setProgress: invoke('app:setProgress'),
    flashFrame: invoke('app:flashFrame'),
    focus: invoke('app:focus'),
    relaunch: invoke('app:relaunch'),
    systemDark: invoke('app:systemDark'),
  },
  store: {
    get: invoke('store:get'),
    set: invoke('store:set'),
    replace: invoke('store:replace'),
    reset: invoke('store:reset'),
  },
  dialog: {
    openFile: invoke('dialog:openFile'),
    openFolder: invoke('dialog:openFolder'),
    saveFile: invoke('dialog:saveFile'),
  },
  fs: {
    writeText: invoke('fs:writeText'),
    readText: invoke('fs:readText'),
    listMedia: invoke('fs:listMedia'),
    ensureDir: invoke('fs:ensureDir'),
    exists: invoke('fs:exists'),
  },
  shell: {
    openPath: invoke('shell:openPath'),
    showItem: invoke('shell:showItem'),
    openExternal: invoke('shell:openExternal'),
    trash: invoke('shell:trash'),
  },
  clipboard: {
    text: invoke('clipboard:text'),
    image: invoke('clipboard:image'),
    readText: invoke('clipboard:readText'),
  },
  adb: {
    devices: invoke('adb:devices'),
    refresh: invoke('adb:refresh'),
    details: invoke('adb:details'),
    screenshot: invoke('adb:screenshot'),
    screenPreview: invoke('adb:screenPreview'),
    install: invoke('adb:install'),
    packages: invoke('adb:packages'),
    appDetails: invoke('adb:appDetails'),
    appAction: invoke('adb:appAction'),
    listDir: invoke('adb:listDir'),
    fileOp: invoke('adb:fileOp'),
    push: invoke('adb:push'),
    pull: invoke('adb:pull'),
    openRemote: invoke('adb:openRemote'),
    keyevent: invoke('adb:keyevent'),
    text: invoke('adb:text'),
    shell: invoke('adb:shell'),
    reboot: invoke('adb:reboot'),
    readSettings: invoke('adb:readSettings'),
    applySetting: invoke('adb:applySetting'),
    connect: invoke('adb:connect'),
    disconnect: invoke('adb:disconnect'),
    pair: invoke('adb:pair'),
    enableWireless: invoke('adb:enableWireless'),
    deviceIp: invoke('adb:deviceIp'),
    mdns: invoke('adb:mdns'),
    restartServer: invoke('adb:restartServer'),
    shellStream: invoke('adb:shellStream'),
    logcat: invoke('adb:logcat'),
    streamStop: invoke('adb:streamStop'),
  },
  scrcpy: {
    start: invoke('scrcpy:start'),
    stop: invoke('scrcpy:stop'),
    stopAll: invoke('scrcpy:stopAll'),
    list: invoke('scrcpy:list'),
    logs: invoke('scrcpy:logs'),
    remove: invoke('scrcpy:remove'),
    clearEnded: invoke('scrcpy:clearEnded'),
    query: invoke('scrcpy:query'),
  },
  camera: {
    info: invoke('camera:info'),
    caps: invoke('camera:caps'),
    conf: invoke('camera:conf'),
    watch: invoke('camera:watch'),
  },
  vcam: {
    status: invoke('vcam:status'),
    install: invoke('vcam:install'),
    uninstall: invoke('vcam:uninstall'),
    start: invoke('vcam:start'),
    stop: invoke('vcam:stop'),
    installed: invoke('vcam:installed'),
  },
  update: {
    status: invoke('update:status'),
    check: invoke('update:check'),
    download: invoke('update:download'),
    install: invoke('update:install'),
    skip: invoke('update:skip'),
  },
  link: {
    info: invoke('link:info'),
    settings: invoke('link:settings'),
    start: invoke('link:start'),
    stop: invoke('link:stop'),
    running: invoke('link:running'),
    volume: invoke('link:volume'),
    setDefaultOutput: invoke('link:setDefaultOutput'),
    open: invoke('link:open'),
    shortcut: invoke('link:shortcut'),
    shortcutExists: invoke('link:shortcutExists'),
    window: invoke('link:window'),
  },
  pair: {
    qrStart: invoke('pair:qrStart'),
    qrCancel: invoke('pair:qrCancel'),
  },
  on: {
    devices: on('devices'),
    scrcpy: on('scrcpy:event'),
    streamData: on('stream:data'),
    streamExit: on('stream:exit'),
    pairStatus: on('pair:status'),
    installProgress: on('install:progress'),
    trayAction: on('tray:action'),
    cameraStatus: on('camera:status'),
    cameraPreview: on('camera:preview'),
    vcamStatus: on('vcam:status'),
    vcamLevel: on('vcam:level'),
    linkStatus: on('link:status'),
    linkLevel: on('link:level'),
    updateStatus: on('update:status'),
    updateShow: on('update:show'),
  },
});
