// Extracts the Lucide icons used by the UI into a small ES module so the
// renderer doesn't need to ship the whole icon set.
const fs = require('fs');
const path = require('path');

const ICONS = `
smartphone monitor-smartphone tablet-smartphone cast play square circle-stop video camera mic volume-2 volume-1 volume-x
wifi wifi-off usb bluetooth plug plug-zap battery battery-charging battery-full battery-medium battery-low battery-warning
cpu hard-drive memory-stick info settings sliders-horizontal terminal square-terminal scroll-text folder folder-open
file file-text file-image file-video file-audio file-archive file-code package box image images film layout-grid list
search x check plus minus trash-2 pencil copy download upload refresh-cw rotate-cw rotate-ccw power house arrow-left
arrow-up arrow-right chevron-left chevron-right chevron-down chevron-up ellipsis-vertical ellipsis external-link link unlink
qr-code radar zap gauge sun moon monitor palette keyboard mouse-pointer-2 gamepad-2 app-window layers star pin lock
lock-open eye eye-off bell circle-alert triangle-alert circle-check circle-x loader-circle sparkles rocket flame leaf
headphones music clapperboard aperture scan maximize minimize crop type send command history save folder-plus clipboard
skip-back skip-forward pause bug activity globe network filter hand pointer fingerprint shield-check wrench code tv
flashlight zoom-in zoom-out sun-dim contrast text-cursor-input circle-dot disc radio list-filter menu panel-left cable
timer clock hash arrow-right-left repeat undo-2 book-open heart circle-help message-square bell-ring moon-star
airplay plane signal circle-power square-play monitor-play monitor-off screen-share app-window-mac arrow-down-to-line
arrow-up-from-line keyboard-off gauge-circle waves blocks store trash layers-2 toggle-left toggle-right accessibility
scan-line scan-eye sun-medium wand-sparkles grip-vertical download-cloud upload-cloud file-plus folder-input folder-output
calendar lightbulb shapes eraser bolt grid-3x3 chart-column flashlight-off focus switch-camera thermometer crosshair flower cloud cloud-sun lamp move mountain square-dashed sliders-vertical webcam
mic-off video-off camera-off speaker audio-lines audio-waveform pin-off
`.trim().split(/\s+/);

const dir = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const out = {};
const missing = [];
for (const name of [...new Set(ICONS)]) {
  const file = path.join(dir, name + '.svg');
  if (!fs.existsSync(file)) { missing.push(name); continue; }
  const svg = fs.readFileSync(file, 'utf8');
  const inner = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
    .replace(/\s*\n\s*/g, '').trim();
  out[name] = inner;
}
const target = path.join(__dirname, '..', 'src', 'renderer', 'js', 'icons.js');
fs.writeFileSync(target, '// Generated by scripts/build-icons.js from lucide-static (ISC License)\nexport const ICONS = ' +
  JSON.stringify(out, null, 0).replace(/","/g, '",\n"') + ';\n');
console.log(`wrote ${Object.keys(out).length} icons`);
if (missing.length) console.log('missing:', missing.join(' '));
